### ISSUE TITLE
Lighthouse: Accessibility: Link text  that is discernible

### ISSUE THREAD

**Issue by ma91n** [future-architect/tech-blog#697]
おそらくli化すれば大丈夫そう

```html
<a target="_blank" rel="noopener" href="https://github.com/future-architect" alt="githubリンク">
<a target="_blank" rel="noopener" href="https://twitter.com/future_techblog" alt="twitterリンク">
<a href="/atom.xml" alt="rssリンク">
```

![image](https://user-images.githubusercontent.com/1751238/118417236-170afd80-b6ee-11eb-8469-e24b18d26044.png)

**Comment by ma91n** [comment]
以下のようにすれば可能だが、この導線はほぼ使われないので消す方向にする。

![image](https://user-images.githubusercontent.com/1751238/118513317-9213f880-b76e-11eb-938d-26ac524fa349.png)

```html
<!-- BEGIN SOCIAL -->
<div class="col-md-6 col-sm-6">
  <ul class="social-footer list-unstyled list-inline pull-right">
    <% for(var s in theme.social) { %>
    <li><a href="<%- url_for(theme.social[s]) %>" alt="<%= s %>リンク"><img src="/css/footer-<%= s %>.svg" alt="<%= s %>" loading="lazy" class="fa fa-<%= s %>"></a></li>
    <% } %>
  </ul>
</div>
<!-- END SOCIAL -->
```

```css
.fa-twitter {
  padding: 1em 1em 0 0;
  display: inline-block;
  background-repeat: no-repeat;
}
.fa-github {
  padding: 1em 1em 0 0;
  display: inline-block;
  background-repeat: no-repeat;
}
.fa-rss {
  padding: 1em 1em 0 0;
  display: inline-block;
  background-repeat: no-repeat;
}
```
